# Install EF Core tools
RUN dotnet tool install --global dotnet-ef --version 8.0.10

# Install Unzip
RUN apt-get update \
    && apt-get install unzip -y

RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install mssql-tools18 unixodbc-dev -y 